name: build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2    
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: subhadeepthandaka/portfolio-multi-tenet:latest

      - name: Verify push
        run: docker pull subhadeepthandaka/portfolio-multi-tenet:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Connection successful!"
            sudo docker pull subhadeepthandaka/portfolio-multi-tenet:latest
            sudo docker stop portfolio || true
            sudo docker rm portfolio || true
            sudo docker run -d -p 3001:3000 \
              --name portfolio \
              -e DATABASE_URL="${{secrets.DATABASE_URL}}" \
              -e JWT_SECRET="${{secrets.JWT_SECRET}}" \
              -e JWT_SECRET_MAIL="${{secrets.JWT_SECRET_MAIL}}" \
              -e RESEND_API_KEY="${{secrets.RESEND_API_KEY}}" \
              subhadeepthandaka/portfolio-multi-tenet:latest

            echo "Running Prisma migrations..."
            sudo docker exec portfolio npx prisma migrate deploy
